### ISSUE TITLE
How to export texture?

### ISSUE THREAD

**Issue by nailcankaratelegram** [ubc-3d-vision-lab/NEO-3DF#2]
Hi. First of all great work!

The local editing in the video is different from the local editing on github. How do we export the texture?
Also is there any way to create edited 2d image from 3d mesh?

Thank you.

**Comment by PeizhiYan** [comment]
Hello, thanks for your interest in our work.

Sorry about the confusion, our demo code only shows how to edit a neutral face shape. We do not reconstruct and edit the texture. You can use Deep3DMM (https://github.com/sicxu/Deep3DFaceRecon_pytorch) to reconstruct both shape and texture from the image and use our method to edit its shape. 

To create a 2D image from the 3D mesh, you can use Pytorch3D's renderer or other 3D renderers. The 3D mesh textures we use are colored vertices, not texture map.
